CRAYSAT-1310: Capture and filter InsecureRequestWarning
Cray-HPE/sat pull request #110
Opened 2023-02-23 18:57 UTC by ekamin-hpe

## Summary and Scope

Add a new warnings.py module with a function to configure warnings.
* Uses 'once' filters and matches API gateway and S3 endpoint parameters
  so that we can get one warning per host.
* Add s3.cert_verify parameter but unfortunately it needs to remain
  False for now.
* Remove TODO references except in config.py where we should eventually
  change the default value of s3.cert_verify.
* Add missing documentation on s3 config file section to the man page.

## Testing

Test Description:
* I ran `sat status` with certificate verification enabled and disabled.
* I ran `sat showrev` with rgw certificate verification enabled and
  disabled.
* I visually inspected the resulting warnings.

## Pull Request Checklist

- [X] Version number(s) incremented, if applicable
- [X] Copyrights updated
- [X] License file intact
- [X] Target branch correct
- [X] CHANGELOG.md updated
- [X] Testing is appropriate and complete, if applicable
- [X] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2023-02-27 17:43 UTC, jack-stanek-hpe approved these changes

2023-04-05 22:24 UTC, haasken-hpe requested changes
It seems like we should make this change in `sat.apiclient.ims` too, so I'm going to make that change and test it out before merging.

2023-04-05 22:24 UTC, haasken-hpe commented on sat/cli/bootsys/state_recorder.py
> -                warnings.filterwarnings('ignore', category=InsecureRequestWarning)
There are some similar `filterwarnings` calls in `sat.apiclient.ims.IMSClient` in the methods for renaming images. I imagine we could similarly get rid of the filtering there too now that we only print one warning for this. I might make that change and test it out with `sat bootprep`.

2023-04-06 23:19 UTC, haasken-hpe commented on sat/cli/bootsys/state_recorder.py
> -                warnings.filterwarnings('ignore', category=InsecureRequestWarning)
Here is the gist with the test results from running `sat bootprep` against an input file that creates an image by configuring an existing image. This exercises the image rename code that uses the S3 API directly. As expected, there is just one warning despite multiple calls to S3 APIs. 

https://gist.github.com/haasken-hpe/5f7b003f1866b75438d3fd60974d43d3

2023-04-06 23:28 UTC, haasken-hpe approved these changes
Looks good to me. @jack-stanek-hpe, could you please give this another review for the additional changes I've made here?

2023-04-06 23:43 UTC, haasken-hpe commented
In testing, I noticed that if you enable cert verification on the IMS requests, you get a traceback in the `sat bootprep` case, so I just pushed a commit to catch that error appropriately. I will test again to make sure that fixes the traceback.

2023-04-07 22:41 UTC, haasken-hpe commented
I updated the gist with the results of testing. I had to switch systems because I was having trouble downloading the image to the system I was working on yesterday.  Here's a link to that gist again: https://gist.github.com/haasken-hpe/5f7b003f1866b75438d3fd60974d43d3

2023-04-07 22:54 UTC, merged