CRAYSAT-1763: Stop supporting --release-files option in sat showrev
Cray-HPE/sat pull request #201
Opened 2024-02-28 10:15 UTC by annapoorna-s-alt

IM: CRAYSAT-1763
Reviewer: Ryan

## Summary and Scope

_From this PR, will stop supporting `--release-files` option in `sat showrev`_

## Issues and Related PRs

_[CRAYSAT-1763](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1763)_

## Testing

_List the environments in which these changes were tested._

### Tested on:

  TO DO

### Test description:

TO DO

## Risks and Mitigations

_Low Risk_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2024-02-28 21:01 UTC, haasken-hpe requested changes
This looks good so far. In addition to my comments, there is one more change I think we should make that I didn't think about when we looked at the Jira together.

I think we should change the behavior of the `--all` option. Since we've changed `--release-files` to just log a warning and not actually look for any release files, we should change the `--all` option to not include it. To do so, I would suggest modifying the function `assign_default_args` to combine the case when `--all` is specified and the case when none of the options are specified into a single case and avoid setting `args.release_files = True` in that situation.

Then, make sure to update the man page for `sat showrev` to reflect the new behavior of both the `--release-files` and the `--all` options. I would also remove the mention of the `/opt/cray/etc/release` directory from the `FILES` section of the man page. That directory has not been populated with any real content from the products for at least a few Shasta releases.

2024-02-29 17:37 UTC, haasken-hpe approved these changes
Looks good! Just needs the man page update. Let me know when it's ready, and I'll review again for that.

2024-03-01 19:31 UTC, haasken-hpe approved these changes
One minor suggestion, but otherwise looks good!

2024-03-04 05:03 UTC, annapoorna-s-alt commented on docs/man/sat-showrev.8.rst
> +        see installed product versions instead.. This option is not enabled by default.
Will address and merge

2024-03-04 05:12 UTC, merged