Adding func to mount ceph/s3fs in ncn-power stage
Cray-HPE/sat pull request #220
Opened 2024-05-31 05:47 UTC by shivaprasad-metimath

IM:CRAYSAT-1582
Reviewer:Ryan

Adding a function to mount ceph and s3fs after checking the ceph health in ncn power stage

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [CRAYSAT-1582](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1582)

## Testing

Yet to be tested 

### Tested on:

  * yet to test 

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2024-06-05 12:26 UTC, shivaprasad-metimath commented
Testing output on fanta system:
[sat_bootsys_ncn-power_output.txt](https://github.com/user-attachments/files/15586406/sat_bootsys_ncn-power_output.txt)

A minor  correct of typo error is also addressed from freeze ceph to unfreeze ceph, as we unfreeze in that steo

2024-06-11 07:34 UTC, shivaprasad-metimath commented
[fanta_system_testing_op.txt](https://github.com/user-attachments/files/15783980/fanta_system_testing_op.txt)
Latest testing done on fanta post changes in the code

2024-06-11 08:02 UTC, annapoorna-s-alt approved these changes
The code changes looks good to me with the latest output.

2024-06-11 22:45 UTC, haasken-hpe requested changes
Since this is using `subprocess` in the container, I don't believe it's really going to detect the ceph and fuse.s3fs filesystems in `/etc/fstab` on ncn-m001 and mount them. It needs to use SSH (Paramiko).

2024-06-11 22:45 UTC, haasken-hpe commented on sat/cli/bootsys/mgmt_power.py
> +            result = subprocess.run(awk_command, shell=True, capture_output=True, text=True, check=True)
Remember that `sat` commands are actually executed in the `cray-sat` container, and this container will not have the same `/etc/fstab` file contents as on the actual ncn-m001 host.

For example, here are the ceph and fuse.s3fs entries from the ncn-m001 host:

```
ncn-m001:~ # awk '{ if ($3 == "ceph") { print; } }' /etc/fstab
admin-tools@.admin-tools=/ /etc/cray/upgrade/csm ceph
ncn-m001:~ # awk '{ if ($3 == "fuse.s3fs") { print; } }' /etc/fstab
sds /var/opt/cray/sdu/collection-mount fuse.s3fs _netdev,allow_other,passwd_file=/root/.sds.s3fs,url=http://rgw-vip.nmn,use_path_request_style,use_cache=/var/lib/s3fs_cache,check_cache_dir_exist,use_xattr,uid=2370,gid=2370,umask=0007,allow_other 0 0
config-data /var/opt/cray/config-data fuse.s3fs _netdev,allow_other,passwd_file=/root/.config-data.s3fs,url=http://rgw-vip.nmn,use_path_request_style,use_xattr 0 0
```

Note that there are no such entries in the sat container:

```
ncn-m001:~ # sat bash
(57bb42e57531) sat-container:/sat/share # awk '{ if ($3 == "ceph") { print; } }' /etc/fstab
(57bb42e57531) sat-container:/sat/share # awk '{ if ($3 == "fuse.s3fs") { print; } }' /etc/fstab
(57bb42e57531) sat-container:/sat/share #
```

I think this means that your code is not actually going to perform any mounts. Instead, you should be using Paramiko (SSH) to execute commands on `ncn-m001`.

2024-06-11 22:45 UTC, haasken-hpe commented on sat/cli/bootsys/mgmt_power.py
> +                result = subprocess.run(["mountpoint", mount_point], capture_output=True, text=True)
Same issue here. This is running in the container, but we really need to execute it on ncn-m001 using SSH.

2024-06-11 22:45 UTC, haasken-hpe commented on sat/cli/bootsys/mgmt_power.py
> +                    subprocess.run(["mount", mount_point], check=True)
Same issue here. This is running in the container, but we really need to execute it on ncn-m001 using SSH.

2024-06-11 22:45 UTC, haasken-hpe commented on sat/cli/bootsys/mgmt_power.py
> +                result = subprocess.run(["mountpoint", mount_point], capture_output=True, text=True)
I would suggest adding more info-level log messages which can show what is being mounted. With these messages, you will be able to see whether the correct filesystems are identified in your testing output. For example:

```suggestion
                LOGGER.info(f'Checking whether {fs_type} filesystem is mounted on {mount_point}.')
                result = subprocess.run(["mountpoint", mount_point], capture_output=True, text=True)
```

2024-06-11 22:45 UTC, haasken-hpe commented on sat/cli/bootsys/mgmt_power.py
> +                    subprocess.run(["mount", mount_point], check=True)
I would suggest adding log messages here to show what's happening as well. E.g.:

```suggestion
                if result.returncode != 0:  # If not a mountpoint, try to mount it
                    LOGGER.info(f'Mounting {fs_type} filesystem on {mount_point}.')
                    subprocess.run(["mount", mount_point], check=True)
                    LOGGER.info(f'Successfully mounted {fs_type} filesystem on {mount_point}.')
                else:
                    LOGGER.info(f'{fs_type} filesystem is already mounted on {mount_point}.')
```

2024-06-11 22:45 UTC, haasken-hpe commented on sat/cli/bootsys/mgmt_power.py
> +        return self.args[0]
It doesn't look like you're really using any of the custom exception handling code here. You're just passing in a `message` when you raise this type of exception. I would suggest simplifying:

```suggestion
    pass
```

2024-06-11 22:50 UTC, haasken-hpe commented
From your testing output:

```
ncn-m002:~ # awk '{ if ($3 == "fuse.s3fs") { print $2; }}' /etc/fstab
/var/opt/cray/sdu/collection-mount
/var/opt/cray/config-data
ncn-m002:~ # awk '{ if ($3 == "ceph") { print $2; }}' /etc/fstab
/etc/cray/upgrade/csm
```

This does not test whether these filesystems are mounted. The file `/etc/fstab` is just a configuration file that tells the node which filesystems should be mounted. It does not tell us which filesystems actually are mounted. To do that, use either `mount` or `findmnt`. For example:

```
ncn-m001:~ # findmnt --type ceph,fuse.s3fs | cat
TARGET                             SOURCE                                                         FSTYPE    OPTIONS
/var/opt/cray/sdu/collection-mount s3fs                                                           fuse.s3fs rw,relatime,user_id=0,group_id=0,allow_other
/var/opt/cray/config-data          s3fs                                                           fuse.s3fs rw,relatime,user_id=0,group_id=0,allow_other
/etc/cray/upgrade/csm              admin-tools@935a29e8-1de2-11ef-8338-b8599f2b2ed2.admin-tools=/ ceph      rw,relatime,name=admin-tools,secret=<hidden>,ms_mode=prefer-crc,acl,mon_addr=10.252.1.5:3300/10.252.1.6:3300/10.252.1.7:3300
```

2024-06-12 16:20 UTC, shivaprasad-metimath commented
Test output post changes: https://gist.github.com/shivaprasad-metimath/ea0d890ee821856c9ed7fb86c63d99ea

Note: A cronjob existed to mount the ceph and s3fs for every minute. Hence had to disable and unmount. I have unmounted only s3fs to have a scenario covered as well

2024-06-12 21:11 UTC, haasken-hpe approved these changes
Looks good. I'll file a Jira for use to look into the cronjob that is automatically mounting the ceph and s3fs filesystems. Perhaps we don't really need this code, but it doesn't hurt anything, especially now that it's nicely logging everything it's checking and telling us if the expected mounts are already there.

Like I mentioned to you in slack, I think it's going to cause us problems if the cron job is attempting to remount these filesystems as we are shutting down. I'll mention that we need to look into this in the Jira I create.

2024-06-12 21:29 UTC, haasken-hpe commented
I created [CRAYSAT-1872](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1872) for us to look into the cron job that auto-mounts ceph and s3fs filesystems.

2024-06-13 04:40 UTC, shivaprasad-metimath commented
Sure Ryan, Thanks for creating a ticket. will go ahead and merge the PR

we can work on the new ticket later.

2024-06-13 04:55 UTC, merged