CRAYSAT-1917: Fix jinja2 rendering of boot_sets data in `sat bootprep`
Cray-HPE/sat pull request #280
Opened 2024-10-30 08:44 UTC by annapoorna-s-alt

## Summary and Scope

Make the following fixes:

- Remove the `boot_set` property from `BaseInputItem`. It is not appropriate there, and it is redundant with `boot_sets` property that already exists in the `InputSessionTemplate`
- Modify the `jinja_rendered` decorator to recursively render more complex objects like lists and dictionaries. I think this is safe, but we should consider any edge cases more carefully.
- Remove the now unnecessary code that does a one-off Jinja2 rendering of `rootfs_provider_passthrough` in the `boot_sets`.

Could still use unit test enhancements that test this new ability to render fields in the boot_sets.

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [CRAYSAT-1917](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1917)

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * starlord

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

Tested on a simple bootprep input file that used a variable in the `rootfs_provider_passthrough` field of a boot set in a BOS session template.

## Risks and Mitigations

_Low_

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [x] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2024-10-30 08:45 UTC, annapoorna-s-alt commented
Testing output on starlord- https://gist.github.com/annapoorna-s-alt/981715de25d248527c7200d50398c731

2024-10-30 08:48 UTC, shivaprasad-metimath commented
Core functionality is tested. Need to update the unit tests for the same.

@annapoorna-s-alt - Would take the ticket forward, as she has tested the draft PR

2024-10-31 07:11 UTC, annapoorna-s-alt commented
Output of testing other fields in the boot_sets support Jinja2 rendering - https://gist.github.com/annapoorna-s-alt/981715de25d248527c7200d50398c731#file-expand-other-fields-with-jinja

2024-11-05 22:24 UTC, haasken-hpe requested changes
The added unit test does not test `jinja_rendered`, which is what is being changed. I have opened a PR to this branch to add such unit tests. Please take a look: https://github.com/Cray-HPE/sat/pull/282

2024-11-05 22:25 UTC, haasken-hpe commented
> Output of testing other fields in the boot_sets support Jinja2 rendering - https://gist.github.com/annapoorna-s-alt/981715de25d248527c7200d50398c731#file-expand-other-fields-with-jinja

This testing looks good.

2024-11-06 15:15 UTC, haasken-hpe approved these changes

2024-11-06 15:19 UTC, merged

2024-11-11 07:06 UTC, annapoorna-s-alt commented
/backport release/3.32